name: Deploy to Inspira Stage
on:
  push:
    branches:
      - stage-desk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Inspira Stage via SSH
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/u296731902/domains/inspira-zentrum.de/public_html/stage-env/
          remote_host: inspira-zentrum.de
          remote_user: u296731902
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
