<?php

return [
    'name' => 'plugins/inspira-cancellation::cancellation.email.title',
    'description' => 'plugins/inspira-cancellation::cancellation.email.description',
    'templates' => [
        'storno_customer' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_customer.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_customer.description',
            'subject' => 'Ihre Stornierung wurde erfasst',
            'can_off' => true,
        ],
        'storno_admin' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_admin.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_admin.description',
            'subject' => 'Neue Stornierung im Inspira Portal',
            'can_off' => true,
        ],
        'storno_refund_approved' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_refund_approved.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_refund_approved.description',
            'subject' => 'Ihre Rückerstattung wurde freigegeben',
            'can_off' => true,
        ],
        'storno_refund_paid' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_refund_paid.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_refund_paid.description',
            'subject' => 'Ihre Rückerstattung wurde ausgezahlt',
            'can_off' => true,
        ],
        'storno_rejected' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_rejected.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.storno_rejected.description',
            'subject' => 'Ihre Stornierung konnte nicht freigegeben werden',
            'can_off' => true,
        ],
        'replacement_old_customer' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_old_customer.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_old_customer.description',
            'subject' => 'Ihre Buchung wurde übertragen',
            'can_off' => true,
        ],
        'replacement_new_customer' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_new_customer.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_new_customer.description',
            'subject' => 'Sie wurden als Ersatzteilnehmer:in eingetragen',
            'can_off' => true,
        ],
        'replacement_admin_request' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_admin_request.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_admin_request.description',
            'subject' => 'Neue Ersatzteilnehmer-Anfrage wartet auf Freigabe',
            'can_off' => true,
        ],
        'replacement_rejected_customer' => [
            'title' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_rejected_customer.title',
            'description' => 'plugins/inspira-cancellation::cancellation.email.templates.replacement_rejected_customer.description',
            'subject' => 'Update zu Ihrer Ersatzteilnehmer-Anfrage',
            'can_off' => true,
        ],
    ],
    'variables' => [
        'booking_reference' => 'plugins/inspira-cancellation::cancellation.email.variables.booking_reference',
        'booking_type' => 'plugins/inspira-cancellation::cancellation.email.variables.booking_type',
        'total_amount' => 'plugins/inspira-cancellation::cancellation.email.variables.total_amount',
        'refund_amount' => 'plugins/inspira-cancellation::cancellation.email.variables.refund_amount',
        'refund_percent' => 'plugins/inspira-cancellation::cancellation.email.variables.refund_percent',
        'fee_amount' => 'plugins/inspira-cancellation::cancellation.email.variables.fee_amount',
        'rule_description' => 'plugins/inspira-cancellation::cancellation.email.variables.rule_description',
        'days_until_start' => 'plugins/inspira-cancellation::cancellation.email.variables.days_until_start',
        'customer_name' => 'plugins/inspira-cancellation::cancellation.email.variables.customer_name',
        'customer_email' => 'plugins/inspira-cancellation::cancellation.email.variables.customer_email',
        'notes' => 'plugins/inspira-cancellation::cancellation.email.variables.notes',
        'new_customer_name' => 'plugins/inspira-cancellation::cancellation.email.variables.new_customer_name',
        'new_customer_email' => 'plugins/inspira-cancellation::cancellation.email.variables.new_customer_email',
        'refund_status' => 'plugins/inspira-cancellation::cancellation.email.variables.refund_status',
        'approver_name' => 'plugins/inspira-cancellation::cancellation.email.variables.approver_name',
        'refund_approved_at' => 'plugins/inspira-cancellation::cancellation.email.variables.refund_approved_at',
        'refund_paid_at' => 'plugins/inspira-cancellation::cancellation.email.variables.refund_paid_at',
        'requested_by' => 'plugins/inspira-cancellation::cancellation.email.variables.requested_by',
        'requested_email' => 'plugins/inspira-cancellation::cancellation.email.variables.requested_email',
    ],
];
